# My Jupyter Notebook on IBM Watson Studio

**Jorge Uriel Cerecero Estrada**
My desired occupation is to be a data scientist

*I'm interested in data science because it's fascinating the way you can tnasform unstructured data into strcutured data that can help you to solve problems*

### i´m going to add two plus two and multiply it by 3 ###

In [1]:
(2+2)*3

12

| Table | Column 1 | Column 2 |
|-----|--------|--------|
| row 1 | example 1 | example 2 |
|-----|--------|--------|
| row 2 | example 3 | example 4 |
|-----|--------|--------|

> This is a example of a blockquotes

---

![alt text](https://images.hola.com/imagenes/mascotas/20221020219416/razas-perros-toy/1-154-385/razas-de-perro-toy-t.jpg "dog image")